- README.md
> initial pull request test

- .travis.yml
- config/config.json
- routes/apiRoutes.js
- routes/htmlRoutes.js
- test/canary.test.js
> Zion branch1

- .travis.yml
> fixed again

- config/config.json
- models/schema.sql
- package.json
- routes/apiRoutes.js
- routes/htmlRoutes.js
Updated api routes page and installed npm packages
> Updated api routes page

- views/layouts/main.handlebars
- views/login.handlebars
- views/signup.handlebars
i fixed the layout for login and signup.handlebars and the main.handlebars
> fixed the layout for the handlebars

- models/example.js
- public/js/index.js
- routes/apiRoutes.js
- routes/htmlRoutes.js
- views/index.handlebars
- views/login.handlebars
- views/signup.handlebars
> Authentication

- public/styles/style.css
- views/layouts/main.handlebars
- views/login.handlebars
- views/signup.handlebars
> minor changes, approve when you can, heres 0

- public/js/index.js
- routes/apiRoutes.js
- routes/htmlRoutes.js
- views/login.handlebars
- views/signup.handlebars
> Routing completed

- public/styles/style.css
- views/login.handlebars
- views/signup.handlebars
> fixed login page

- models/example.js
- public/js/index.js
- routes/apiRoutes.js
- routes/htmlRoutes.js
- views/login.handlebars
- views/signup.handlebars
- views/welcome.handlebars
> Welcome Page created

- views/signup.handlebars
> Updated signup page

- models/messages.js
- public/js/index.js
- routes/apiRoutes.js
- routes/htmlRoutes.js
- views/welcome.handlebars
Message Tables updated and showing the messages on screen now
> Message Tables updated and showing the messages on screen now

- package-lock.json
- package.json
- public/js/index.js
- public/styles/style.css
- views/layouts/main.handlebars
- views/welcome.handlebars
> minor changes

- views/welcome.handlebars
removed bullet point from each of the chat lines - cleaner look
> minor change: removed bullet point from each line in chat. Cleaner look.

- server.js
- views/welcome.handlebars
Configured number of users shown
> Configured number of users

- models/channels.js
- models/messages.js
- public/js/index.js
- public/styles/style.css
- views/welcome.handlebars
> Make code more readable

- public/js/index.js
- server.js
- views/welcome.handlebars
Added a feature to show if someone is typing
> Added a feature to show if someone is typing

- public/js/index.js
Avoided < and > sign and made username bold
> Avoided < and > sign

- public/js/index.js
> Changed the username to bold

- config/middleware/isAuthenticated.js
> Fixed Login failed page

- public/js/index.js
> Fixed minor issue

- views/login.handlebars
- views/signup.handlebars
> Minor change

- README.md
- config/middleware/isAuthenticated.js
- config/passport.js
- models/user.js
- public/js/index.js
- routes/apiRoutes.js
- routes/htmlRoutes.js
> Commented Code

- public/js/index.js
- routes/apiRoutes.js
- routes/htmlRoutes.js
- views/login.handlebars
- views/signup.handlebars
- views/welcome.handlebars
Included Change password feature
> Included Change password feature

- public/js/index.js
- routes/apiRoutes.js
- views/welcome.handlebars
Avoid duplicating data when changing username
> Avoid duplicating data when changing username

- views/welcome.handlebars
> Configured Burger Menu

- public/styles/style.css
- routes/apiRoutes.js
- routes/htmlRoutes.js
- views/login.handlebars
- views/signup.handlebars
- views/welcome.handlebars
I moved some style="" tags to the css file.
> Settings branch
